#!/bin/bash

ERRORS=0
FLAKES=$(flake8 dput bin -r)
FLAKE_RET=$?

#if [ "x$FLAKES" != "x" ]; then
#    echo "$FLAKES"
#fi

WARNINGS=$(make -C docs html 2>&1 >/dev/null | grep WARNING)
DOC_RET=$?
#if [ "x$WARNINGS" != "x" ]; then
#    echo "$WARNINGS"
#fi
nosetests 2> /dev/null
NOSE_RET=$?

if [ $FLAKE_RET -ne 0 ]; then
    echo "[[31m NO [0m]   you've got flake issues."
    let ERRORS=$ERRORS+1
else
    echo "[[32m OK [0m]   flake8 clean."
fi
if [ $DOC_RET -ne 0 ]; then
    echo "[[31m NO [0m]   docs don't make properly"
    let ERRORS=$ERRORS+1
else
    echo "[[32m OK [0m]   docs make"
fi
if [ "x$WARNINGS" != "x" ]; then
    echo "[[31m NO [0m]   docs have warnings. fix them."
    let ERRORS=$ERRORS+1
else
    echo "[[32m OK [0m]   docs make without warning."
fi
if [ $NOSE_RET -ne 0 ]; then
    echo "[[31m NO [0m]   you've got test issues."
    let ERRORS=$ERRORS+1
else
    echo "[[32m OK [0m]   tests pass."
fi

if [ $ERRORS -ne 0 ]; then
    echo "[ [1;31mNO[0m ]   [1mDO NOT COMMIT THIS. - $ERRORS ERRORS[0m"
fi

exit $ERRORS
